#!/usr/bin/env python3
"""
Generate `Src/adc_percent_pots_lut.c` in this directory (firmware/LUT).

Pedal position: four 0–100% tables (12-bit index), each with its own end-stop band.
Brake pressure PSI: 0.5 V = 0 PSI, 4.5 V = 3000 PSI, with V = (ADC/4095)*VREF (VREF=3.3 V).
"""
import os
import sys

SIZE = 4096
OUT_OF_RANGE = 0
VREF = 3.3  # must match board ADC reference in firmware

# ---------------- BRAKE PEDAL — MAIN (PA2) ----------------
BRAKE_MAIN_MIN_LOW = 45
BRAKE_MAIN_MIN_HIGH = 52
BRAKE_MAIN_MAX_LOW = 3500
BRAKE_MAIN_MAX_HIGH = 3600

# ---------------- BRAKE PEDAL — REDUNDANT (PB0) ----------------
BRAKE_REDUNDANT_MIN_LOW = 45
BRAKE_REDUNDANT_MIN_HIGH = 52
BRAKE_REDUNDANT_MAX_LOW = 3500
BRAKE_REDUNDANT_MAX_HIGH = 3600

# ---------------- ACCEL PEDAL — MAIN (PA0) ----------------
ACCEL_MAIN_MIN_LOW = 95
ACCEL_MAIN_MIN_HIGH = 106
ACCEL_MAIN_MAX_LOW = 650
ACCEL_MAIN_MAX_HIGH = 700

# ---------------- ACCEL PEDAL — REDUNDANT (PA6) ----------------
ACCEL_REDUNDANT_MIN_LOW = 95
ACCEL_REDUNDANT_MIN_HIGH = 106
ACCEL_REDUNDANT_MAX_LOW = 650
ACCEL_REDUNDANT_MAX_HIGH = 700

# ---------------- BRAKE PRESSURE 1 (FL FRONT) % / travel (optional) ----------------
BRAKE_PRESSURE1_MIN_LOW = 200
BRAKE_PRESSURE1_MIN_HIGH = 220
BRAKE_PRESSURE1_MAX_LOW = 3500
BRAKE_PRESSURE1_MAX_HIGH = 3600

# ---------------- BRAKE PRESSURE 2 (FL BACK) % / travel (optional) ----------------
BRAKE_PRESSURE2_MIN_LOW = 200
BRAKE_PRESSURE2_MIN_HIGH = 220
BRAKE_PRESSURE2_MAX_LOW = 3500
BRAKE_PRESSURE2_MAX_HIGH = 3600

# ---------------- BRAKE PRESSURE PSI (0.5 V = 0 PSI, 4.5 V = 3000 PSI) ----------------
# Physical sensor span; V = (ADC count / 4095) * VREF
V_PSI_MIN = 0.5
V_PSI_MAX = 4.5
PSI_MAX = 3000.0


def compute_percent(i, min_low, min_high, max_low, max_high):
    if i < min_low or i > max_high:
        return OUT_OF_RANGE
    if min_low <= i <= min_high:
        return 0
    if max_low <= i <= max_high:
        return 100
    span = max_low - min_high
    return ((i - min_high) * 100) // span


def write_lut(f, name, min_low, min_high, max_low, max_high):
    f.write(f"const uint8_t {name}[4096] = {{\n")
    for i in range(SIZE):
        percent = compute_percent(i, min_low, min_high, max_low, max_high)
        f.write(f"{percent}")
        if i < SIZE - 1:
            f.write(", ")
        if (i + 1) % 16 == 0:
            f.write("\n")
    f.write("\n};\n\n")


def brake_psi_tenths_from_adc_count(i: int) -> int:
    """DBC Brake_Pressure scale 0.1 PSI: store PSI*10, max 3000 PSI -> 30000."""
    v = i * VREF / 4095.0
    if v <= V_PSI_MIN:
        psi = 0.0
    elif v >= V_PSI_MAX:
        psi = PSI_MAX
    else:
        psi = (v - V_PSI_MIN) / (V_PSI_MAX - V_PSI_MIN) * PSI_MAX
    t = int(round(psi * 10.0))
    if t < 0:
        t = 0
    if t > 30000:
        t = 30000
    return t


def write_brake_psi_tenths_lut(f) -> None:
    f.write(
        f"/* 0.5 V = 0 PSI, 4.5 V = 3000 PSI; V = (ADC/4095)*{VREF} V */\n"
    )
    f.write("const uint16_t brakePressurePsiTenthsLUT[4096] = {\n")
    for i in range(SIZE):
        t = brake_psi_tenths_from_adc_count(i)
        f.write(f"{t}")
        if i < SIZE - 1:
            f.write(", ")
        if (i + 1) % 12 == 0:
            f.write("\n")
    f.write("\n};\n\n")


def main() -> int:
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Src")
    out_path = os.path.join(out_dir, "adc_percent_pots_lut.c")
    os.makedirs(out_dir, exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("#include <stdint.h>\n\n")
        f.write("/* --------------------------------------------------\n")
        f.write("    Pedal position: main + redundant LUTs; brake pressure PSI + %% helpers\n")
        f.write("    Generated by generateLUTs.py — do not edit by hand\n")
        f.write("   -------------------------------------------------- */\n\n")

        write_lut(
            f,
            "adcPercentBrakeMainLUT",
            BRAKE_MAIN_MIN_LOW,
            BRAKE_MAIN_MIN_HIGH,
            BRAKE_MAIN_MAX_LOW,
            BRAKE_MAIN_MAX_HIGH,
        )
        write_lut(
            f,
            "adcPercentBrakeRedundantLUT",
            BRAKE_REDUNDANT_MIN_LOW,
            BRAKE_REDUNDANT_MIN_HIGH,
            BRAKE_REDUNDANT_MAX_LOW,
            BRAKE_REDUNDANT_MAX_HIGH,
        )
        write_lut(
            f,
            "adcPercentAccelMainLUT",
            ACCEL_MAIN_MIN_LOW,
            ACCEL_MAIN_MIN_HIGH,
            ACCEL_MAIN_MAX_LOW,
            ACCEL_MAIN_MAX_HIGH,
        )
        write_lut(
            f,
            "adcPercentAccelRedundantLUT",
            ACCEL_REDUNDANT_MIN_LOW,
            ACCEL_REDUNDANT_MIN_HIGH,
            ACCEL_REDUNDANT_MAX_LOW,
            ACCEL_REDUNDANT_MAX_HIGH,
        )

        write_lut(
            f,
            "adcPercentBrakePressure1LUT",
            BRAKE_PRESSURE1_MIN_LOW,
            BRAKE_PRESSURE1_MIN_HIGH,
            BRAKE_PRESSURE1_MAX_LOW,
            BRAKE_PRESSURE1_MAX_HIGH,
        )
        write_lut(
            f,
            "adcPercentBrakePressure2LUT",
            BRAKE_PRESSURE2_MIN_LOW,
            BRAKE_PRESSURE2_MIN_HIGH,
            BRAKE_PRESSURE2_MAX_LOW,
            BRAKE_PRESSURE2_MAX_HIGH,
        )

        write_brake_psi_tenths_lut(f)

    print(f"Lookup tables written to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
